name: Build and Test Fortran Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: intel
          version: '2024.1'

      - name: Build Fortran code using Makefile
        run: |
          cd src
          make clean || true
          ifort --version || true
          make fortran_compiler=ifort FFLAGS="-O2" 2>&1 | tee build.log

      - name: Check executable exists
        run: |
          test -f src/Anura3D.out
          ls -lah src/Anura3D.out

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: src/build.log
